name: "ASCII Art Generation using Cowsay"
on: push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout the repo"
          uses: actions/checkout@v4
        - name: "Install Cowsay"
          run: sudo apt-get install -y cowsay
        - name: "Execute the Cowsay command"
          run: | 
            cowsay -f dragon "Run boy run a Dragon is in town" >> dragon.txt
            grep -i "dragon" dragon.txt
        