name: "My First Workflow"
on: push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Inspect"
        run: |
          echo "Inspecting Git Repo"
          ls -lart
          cat README.md

            



